language: node_js
node_js:
  - "7"
  
before_script:
  - npm install
  
script:
  - echo "Antes de la construcción"
  - npm run build
  -ls

deploy:
  provider: pages
  local -dir: build/
  skip_cleanup: true
  gthub_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
